### ISSUE TITLE
(Verbose) mode to display line contents

### ISSUE THREAD

**Issue by blueyed** [Bachmann1234/diff_cover#134]
Currently only line numbers get displayed.

I think it would be useful to also display the missing lines verbatim, especially for CI, where a merge is tested, and line numbers might be different from the branch itself.

**Comment by Bachmann1234** [comment]
IM game for it. Seems like a reasonable thing to add

**Comment by maho** [comment]
I second that: it would be nice, if things which are in htmlreport, are also in output of diff-cover

**Comment by kasium** [comment]
Hi,

I took a look into this and found out, that diff-cover already supports a terminal output which is just not used
https://github.com/Bachmann1234/diff_cover/blob/14e3d4d388e8815a96757efd9ec252fdd52409df/diff_cover/snippets.py#L130-L140

Unfortunately, the lines which are not covered are not highlighted as in the html report. 
I guess we should decide if this is fine or if we need highlighting. If yes, one option is to modify the token stream or to implement a custom lexer.

Also, we should decide how the CLI flag should be called. I'm not sure if "-v" is nice, because I would reserve it for extended logging.

@Bachmann1234 can you please share your opinion?

**Comment by Bachmann1234** [comment]
So yeah the markdown formatter was added as part of this PR https://github.com/Bachmann1234/diff_cover/pull/164

You can see the back and forth. Markdown was a bit of an experiment that I guess we never followed though on. 

Im sorta thinking highlighting is not terribly important if we are talking about a feature for CI workflows

**Comment by kasium** [comment]
Thanks for the insights. If you don't mind, I can add it hidden by a flag. Any suggestions how to call it?

**Comment by kasium** [comment]
Hi @maho @Bachmann1234,
i have created a short draft how it could look like. Maybe you can download the patch and take a look? The CLI option is "--show-uncovered"

**Comment by Bachmann1234** [comment]
@kasium @maho This is released https://pypi.org/project/diff-cover/5.4.0/

**Comment by blueyed** [comment]
I've just tested this using `--show-uncovered`, but noticed that the line numbers are off: they start with 1 for every displayed hunk, and therefore it is not possible to tell which line(s) are uncovered.

E.g.
```
% diff-cover --compare-branch main --fail-under=100 --show-uncovered --html-report build/diff-cover-report.html build/coverage.xml
-------------
Diff Coverage
Diff: main...HEAD, staged and unstaged changes
-------------
…
foo/models.py (84.6%): Missing lines 29,37
…
-------------
Total:   472 lines
Missing: 6 lines
Coverage: 98%
-------------

--- foo/models.py ---

0001:     class Meta:
0002:         unique_together = ("a", "b")
0003:
0004:     def __repr__(self) -> str:
0005:         return (
0006:             f"X(id={self.id},"
0007:             f" …"
0008:             f" …"
0009:             f" …)"




0001:             f" …)"
0002:         )
0003:
0004:     def __str__(self) -> str:
0005:         return (
0006:             …
0007:             …
0008:         )
0009:         # return (

…

Failure. Coverage is below 100%.
```

**Comment by kasium** [comment]
I guess this is a general issue with the templates. So also markdown and html reports are affected as far as I can tell
