### ISSUE TITLE
No description on pypi

### ISSUE THREAD

**Issue by kasium** [Bachmann1234/diff_cover#228]
Diff-cover has no description on pypi, but it would be nice to have a short one: https://pypi.org/project/diff-cover/
Also a link to the Changelog, would be very nice

**Comment by Bachmann1234** [comment]
So it used to have one. The description was the readme and if you look at
the setup.py I think it still is.  The problem is it does not parse
correctly. I tried to fix it a few times and have failed. I have not gotten
a terribly useful error back from pypi.

But I guess I can give it another shot..maybe this weekend

**Comment by kasium** [comment]
As you might remember I fixed a few issues in the README, maybe this already solved the issue.
I can also let a RST linter check the file, maybe this helps

**Comment by kasium** [comment]
#229 I have found a few flaws and directly added a linter

**Comment by Bachmann1234** [comment]
Hey! That worked! Awesome!

https://pypi.org/project/diff-cover/6.2.1/

**Comment by kasium** [comment]
great!
