### ISSUE TITLE
total quality % should be calculated based on the real lines to check

### ISSUE THREAD

**Issue by agroszer** [Bachmann1234/diff_cover#36]
e.g. pylint cares only about .py extensions, can happen that the diff has a boatload of .txt changes (which will be considered as 100%), that influences the quality in the wrong direction

**Comment by Bachmann1234** [comment]
:+1: like the idea. Probably should be based on the extension for the particular quality tool. Gets a bit tricker with coverage since technically you can combine reports from several languages. Ill add a node to the TODO though this is open for someone else to grab as well.

**Comment by agroszer** [comment]
I have this in the pipeline

**Comment by kasium** [comment]
@agroszer @Bachmann1234 I just checked this issue here and it seems it's already implemented. If you change a python file and a txt file and run diff-quality with flake8, only the python file is considered.
This is done by the supported_extensions settings in teh flake8 driver. Same applies to pylint.
