### ISSUE TITLE
Diff between two coverage files instead of coverage file from branch

### ISSUE THREAD

**Issue by mbestipa** [Bachmann1234/diff_cover#374]
Hi there. Thank you for this awesome tool.

I'm running coverage reports for python in the ci with py-cov. I'm currently uploading the coverage report as an artifact, and I would like to compare it with the coverage report from the artifacts of the main branch. I'm doing this because I don't want to go through a third party tool like codecov in order to check the diff, and I don't want to save the coverage as a file in the repo itself.

I'm wondering if anyone else has run into this, and whether it make sense to enable the functionality of comparing between two coverage files instead of a given coverage file and the coverage file from a specified branch.

**Comment by Bachmann1234** [comment]
So my first instinct is that this would not be something for diff-cover. I think its the kind of thing that would be a separate tool entirely. Ill explain

Diff-cover asks for a branch because thats how it generates the diff thats used to do the comparison. If we are saying "Dont worry about the branch and diff the file" we threw out a the core that is diff cover. The repo and the git diff.

What you are describing (at least to me) sounds more like a specialized text diff. Given two reports, parse them, highlight where coverage increased and where it decreased. 

No need for git, no need for source code or the repo itself. The only thing diff cover would be providing potentially is the ability to read the reports (but I think you will find diff cover's parsing of these reports is not terribly deep)

My point is I think a specialized/simpler tool for this would make more sense.

**Comment by mbestipa** [comment]
Hi @Bachmann1234.
Thanks for responding to this, your explanation makes sense to me.
I'll write a separate script, and close this issue. Thanks again for your work 👍
