### ISSUE TITLE
diff-quality doesn't work with eslint

### ISSUE THREAD

**Issue by godlark** [Bachmann1234/diff_cover#81]
I have a git repo with python and javascript files. The structure is:
```
- docker
- scripts
- my_project
--- static
------ .eslintrc.js
------ package.json
------ js
--- app1
--- app2
```
The structure is typical for django projects.
Eslint generates reports with absolute path by default, e.g.
`/home/godlark/PycharmProjects/mye_repo/my_project/static/js/index.js`
but `diff-quality` expects paths relative to the root directory of repo, e.g.
`my_projects/static/js/index.js`
I was able to create a custom formatter for eslint to generate reports with relative path, e.g.
`js/index.js`
But it still doesn't match. The solution is to run in `diff-cover` command `git diff --relative` instead `git diff`

**Comment by kasium** [comment]
Hi,

just found this issue. I guess making the paths as diff-cover needs them is not too complicated. I see this on our side since eslint refuses to support relative paths in reports (https://github.com/eslint/eslint/issues/13376).

My approach would be:
1. Make the paths relative to the got repository
2. In the case the report was generated on another machine, the part which we want to remove can differ. Therefore a new cli parameter defining the "root" could help

Report
```
/root/git/repo/a.js: foo
```

Same machine: Our git path would be "/root/git/repo" --> `a.js`

Other machine with the path `/usr/foo/git/a.js` --> `diff-quality --violations eslint --repo-path "/root/git/repo" report.txt` --> `a.js`

@Bachmann1234 what do you think about this? Any suggestion for the cli name?

**Comment by Bachmann1234** [comment]
maybe 'base-path' ? or 'root-path'? Or maybe 'repo-root'. Something to imply a root right?

**Comment by kasium** [comment]
@Bachmann1234 I'm sorry for the late follow-up. Currently I stuck how to give the root_path to the quality driver w/o breaking the API of the quality driver.

I cannot give it in the constructor since it's defined in the CLI, but also the parse_reports doesn't work w/o adding another pameter.

Any idea?

**Comment by Bachmann1234** [comment]
Is adding an optional kwarg not an option?

IF we wanna break the api a bit I wanna say its possible. I have not gotten
signals that many people have made plugins. I think we could just contact
the SQLFluff project and either provide them a PR or just coordinate.

When we release this i'll increment a major version.

-Matt Bachmann

**Comment by Bachmann1234** [comment]
Try out https://pypi.org/project/diff-cover/6.4.0/ thanks @kasium for the PR !
